### ISSUE TITLE
You might actually describe what happened instead of using vague fluff and linking to a tweet with more vague fluff

### ISSUE THREAD

**Issue by XANi** [mena-devs/open_letter#22]
"Breaking CoC" isnt' exactly useful explaination of what happened

**Comment by Link-** [comment]
@XANi Your comment is spot on and quite common. 

For one, the details of the incident are unknown to us. yet they were sufficient enough for JSConfEU to release a public blogpost warning speakers and potential attendees not to be part of JSConf Beirut and withdraw their support. For two, we do agree with JSConfEU that we all make mistakes, and in order to protect those involved and the innocent, it's best if the details are limited to "Breaking CoC". For three, the purpose of this letter is: to clarify to the global community that this incident is not a reflection of our modus operandi as a local community or how we organize events and that in fact, Beirut, is a great location to host conferences, seminars and the likes. Anything beyond that is irrelevant, and given that our response was made public, it's time to move forward.

**Comment by constantine-nikolaou** [comment]
@XANi we've tried to get further information when we saw JSConf EU tweet/blogpost but our efforts were unsuccessful since both parties agreed not to share further details.
We have a very vibrant talented community in Lebanon, mostly centred around Beirut, and we found it unfair that one single incident that we don't know much about to reflect negatively on the community.
Thanks for reaching out though and we're happy to help if you have further questions.
